spring:
  datasource:
    name: user-connection
    url: jdbc:mysql://127.0.0.1:3306/user
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-active: 100
      max-wait: 10000
      max-idle: 100
      min-idle: 1
      remove-abandoned-timeout: 60
      remove-abandoned: true
      initial-size: 10
  jpa:
    properties:
    hibernate:
        hbm2ddl:
          auto: update
server:
  port: 9999
  context-path: /user
  max-http-header-size: 8192
  tomcat:
    max-http-post-size: 4096
    max-connections: 20000
    max-threads: 150