server:
  port: 10002
eureka:
  instance:
    prefer-ip-address: true
    hostname: web
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8760/eureka/
#      defaultZone: http://aa:abcd@localhost:8760/eureka/

feign:
  httpclient:
    enabled: true
  hystrix:
   enabled: true
spring:
  application:
    name: web